<HTML>
<HEAD>
<meta charset="UTF-8">
<title>NestedIOException - spring-framework</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">spring-framework</a>&nbsp;/&nbsp;<a href="../index.html">org.springframework.core</a>&nbsp;/&nbsp;<a href=".">NestedIOException</a><br/>
<br/>
<h1>NestedIOException</h1>
<code><span class="keyword">open</span> <span class="keyword">class </span><span class="identifier">NestedIOException</span>&nbsp;<span class="symbol">:</span>&nbsp;<span class="identifier">IOException</span></code>
<p>Subclass of IOException that properly handles a root cause, exposing the root cause just like NestedChecked/RuntimeException does. 
<p>Proper root cause handling has not been added to standard IOException before Java 6, which is why we need to do it ourselves for Java 5 compatibility purposes. </p>
<p>The similarity between this class and the NestedChecked/RuntimeException class is unavoidable, as this class needs to derive from IOException.</p>
</p>
<p><strong>Author</strong><br/>
Juergen Hoeller</p>
<p><strong>Since</strong><br/>
2.0</p>
<p><strong>See Also</strong><br/>
<a href="#">#getMessage</a><a href="#">#printStackTrace</a>org.springframework.core.NestedCheckedExceptionorg.springframework.core.NestedRuntimeException</p>
<h3>Constructors</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="-init-.html">&lt;init&gt;</a></p>
</td>
<td>
<code><span class="identifier">NestedIOException</span><span class="symbol">(</span><span class="identifier" id="org.springframework.core.NestedIOException$<init>(kotlin.String)/msg">msg</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a><span class="symbol">)</span></code>
<p>Construct a <code>NestedIOException</code> with the specified detail message.</p>
<code><span class="identifier">NestedIOException</span><span class="symbol">(</span><span class="identifier" id="org.springframework.core.NestedIOException$<init>(kotlin.String, kotlin.Throwable)/msg">msg</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a><span class="symbol">, </span><span class="identifier" id="org.springframework.core.NestedIOException$<init>(kotlin.String, kotlin.Throwable)/cause">cause</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">)</span></code>
<p>Construct a <code>NestedIOException</code> with the specified detail message and nested exception.</p>
</td>
</tr>
</tbody>
</table>
<h3>Properties</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="message.html">message</a></p>
</td>
<td>
<code><span class="keyword">open</span> <span class="keyword">val </span><span class="identifier">message</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a></code>
<p>Return the detail message, including the message from the nested exception if there is one.</p>
</td>
</tr>
</tbody>
</table>
</BODY>
</HTML>
