<HTML>
<HEAD>
<meta charset="UTF-8">
<title>MetaDataAccessException - spring-framework</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">spring-framework</a>&nbsp;/&nbsp;<a href="../index.html">org.springframework.jdbc.support</a>&nbsp;/&nbsp;<a href=".">MetaDataAccessException</a><br/>
<br/>
<h1>MetaDataAccessException</h1>
<code><span class="keyword">open</span> <span class="keyword">class </span><span class="identifier">MetaDataAccessException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="../../org.springframework.core/-nested-checked-exception/index.html"><span class="identifier">NestedCheckedException</span></a></code>
<p>Exception indicating that something went wrong during JDBC metadata lookup. 
<p>This is a checked exception since we want it to be caught, logged and handled rather than cause the application to fail. Failure to read JDBC metadata is usually not a fatal problem.</p>
</p>
<p><strong>Author</strong><br/>
Thomas Risberg</p>
<p><strong>Since</strong><br/>
1.0.1</p>
<h3>Constructors</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="-init-.html">&lt;init&gt;</a></p>
</td>
<td>
<code><span class="identifier">MetaDataAccessException</span><span class="symbol">(</span><span class="identifier" id="org.springframework.jdbc.support.MetaDataAccessException$<init>(kotlin.String)/msg">msg</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a><span class="symbol">)</span></code><br/>
<code><span class="identifier">MetaDataAccessException</span><span class="symbol">(</span><span class="identifier" id="org.springframework.jdbc.support.MetaDataAccessException$<init>(kotlin.String, kotlin.Throwable)/msg">msg</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a><span class="symbol">, </span><span class="identifier" id="org.springframework.jdbc.support.MetaDataAccessException$<init>(kotlin.String, kotlin.Throwable)/cause">cause</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">)</span></code>
<p>Constructor for MetaDataAccessException.</p>
</td>
</tr>
</tbody>
</table>
<h3>Inherited Properties</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="../../org.springframework.core/-nested-checked-exception/message.html">message</a></p>
</td>
<td>
<code><span class="keyword">open</span> <span class="keyword">val </span><span class="identifier">message</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a></code>
<p>Return the detail message, including the message from the nested exception if there is one.</p>
</td>
</tr>
</tbody>
</table>
<h3>Inherited Functions</h3>
<table>
<tbody>
<tr>
<td>
<p><a href="../../org.springframework.core/-nested-checked-exception/contains.html">contains</a></p>
</td>
<td>
<code><span class="keyword">open</span> <span class="keyword">fun </span><span class="identifier">contains</span><span class="symbol">(</span><span class="identifier" id="org.springframework.core.NestedCheckedException$contains(java.lang.Class((kotlin.Any)))/exType">exType</span><span class="symbol">:</span>&nbsp;<span class="identifier">Class</span><span class="symbol">&lt;</span><span class="identifier">*</span><span class="symbol">&gt;</span><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-boolean/index.html"><span class="identifier">Boolean</span></a></code>
<p>Check whether this exception contains an exception of the given type: either it is of the given class itself or it contains a nested cause of the given type.</p>
</td>
</tr>
<tr>
<td>
<p><a href="../../org.springframework.core/-nested-checked-exception/get-most-specific-cause.html">getMostSpecificCause</a></p>
</td>
<td>
<code><span class="keyword">open</span> <span class="keyword">fun </span><span class="identifier">getMostSpecificCause</span><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a></code>
<p>Retrieve the most specific cause of this exception, that is, either the innermost cause (root cause) or this exception itself. 
<p>Differs from <code><a href="../../org.springframework.core/-nested-checked-exception/get-root-cause.html">#getRootCause()</a></code> in that it falls back to the present exception if there is no root cause.</p>
</p>
</td>
</tr>
<tr>
<td>
<p><a href="../../org.springframework.core/-nested-checked-exception/get-root-cause.html">getRootCause</a></p>
</td>
<td>
<code><span class="keyword">open</span> <span class="keyword">fun </span><span class="identifier">getRootCause</span><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a></code>
<p>Retrieve the innermost cause of this exception, if any.</p>
</td>
</tr>
</tbody>
</table>
</BODY>
</HTML>
